### ISSUE TITLE
Howdy does not function, cannot find module dlib despite dlib being installed.

### ISSUE THREAD

**Issue by ccwky11** [boltgolt/howdy#488]
As noted above, I cannot use howdy as when attempting to run howdy it fails as seen in the screenshot below
![image](https://user-images.githubusercontent.com/62629038/103451585-57139b80-4c8b-11eb-8a76-3e0b1a3788e8.png)
Any help or advice would be much appreciated, and thank you for this program, I have been using it since I began using Linux about 2 years ago and it is really one of the most impactful programs I have yet used.

**Comment by ilkhem** [comment]
I also have this problem since the latest Manjaro update (it was working fine with the experimental 5.10 kernel, but broke once I upgraded to 5.10 LTS)

**Comment by ccwky11** [comment]
Having attempted ilkhem's suggestion, I am still unable to get howdy working, I get the same error that no module is named dlib.

**Comment by kxxt** [comment]
I also get this error after manjaro system upgrade.
I installed dlib, but it didn't solve the issue.
Now I'm trying to reinstall howdy.

**Comment by catbabylon** [comment]
same issue on fedora 34 beta. I installed Howdy, then saw the dlib error as above, I installed dlib, same error message, I reinstalled howdy, same error message.

**Comment by gabrieleaquaro** [comment]
In Fedora i  solved with :
`sudo dnf install python3-dlib`
